{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 info pnpm": {
    "err": {
      "name": "Error",
      "message": "not found: -g",
      "code": "ENOENT",
      "stack": "Error: not found: -g\n    at getNotFoundError (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:41518:51)\n    at Function.whichSync [as sync] (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:41595:13)\n    at getCommandAbsolutePathSync (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:43160:44)\n    at default_1 (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:43169:32)\n    at /Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:171243:39"
    }
  },
  "2 error pnpm": {
    "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
    "prefix": "/Users/renya/Library/pnpm/global/5",
    "err": {
      "name": "pnpm",
      "message": "not found: -g",
      "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
      "stack": "Error: not found: -g\n    at getNotFoundError (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:41518:51)\n    at Function.whichSync [as sync] (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:41595:13)\n    at getCommandAbsolutePathSync (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:43160:44)\n    at default_1 (/Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:43169:32)\n    at /Users/renya/.nvm/versions/node/v16.5.0/lib/node_modules/pnpm/dist/pnpm.cjs:171243:39"
    }
  }
}